// Copyright (C) 2026 Yisi Yu
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

#ifndef NES_NES_BUILDFLAGS_H_
#define NES_NES_BUILDFLAGS_H_

#include "build/buildflag.h"

#if !defined(KIWI_ENABLE_APU_FRAME_BOUNDARY_CLOCK_FIX)
#define KIWI_ENABLE_APU_FRAME_BOUNDARY_CLOCK_FIX 1
#endif

#if !defined(KIWI_ENABLE_INES1_TV_SYSTEM_FIX)
#define KIWI_ENABLE_INES1_TV_SYSTEM_FIX 1
#endif

// Mapper support is always built into Kiwi.
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_013() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_016() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_018() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_019() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_021() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_022() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_023() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_024() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_025() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_026() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_032() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_034() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_037() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_038() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_041() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_046() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_047() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_064() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_065() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_067() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_068() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_069() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_070() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_071() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_072() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_073() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_077() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_078() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_079() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_080() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_085() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_086() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_089() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_092() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_093() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_094() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_096() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_097() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_104() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_105() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_112() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_113() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_115() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_118() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_119() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_132() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_133() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_137() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_139() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_140() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_141() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_143() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_146() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_147() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_148() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_150() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_156() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_168() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_176() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_177() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_178() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_180() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_184() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_186() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_188() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_189() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_193() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_206() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_216() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_228() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_232() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_234() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_240() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_241() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_244() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_245() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_246() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_355() (1)
#define BUILDFLAG_INTERNAL_ENABLE_MAPPER_512() (1)
#define BUILDFLAG_INTERNAL_ENABLE_APU_FRAME_BOUNDARY_CLOCK_FIX() \
  (KIWI_ENABLE_APU_FRAME_BOUNDARY_CLOCK_FIX)
#define BUILDFLAG_INTERNAL_ENABLE_INES1_TV_SYSTEM_FIX() \
  (KIWI_ENABLE_INES1_TV_SYSTEM_FIX)

#endif  // NES_NES_BUILDFLAGS_H_
